import { Router } from "express";
import fs from "fs/promises";
import path from "path";
import os from "os";

const router = Router();

interface ForgeFile { path: string; content: string }

router.post("/tool-forge", async (req, res) => {
  const { description } = req.body as { description?: string };
  if (!description || description.length < 5) {
    res.status(400).json({ error: "description required (min 5 chars)" });
    return;
  }

  const skillName = description
    .toLowerCase()
    .replace(/[^a-z0-9 ]/g, "")
    .trim()
    .split(/\s+/)
    .slice(0, 4)
    .join("-");

  const skillMd = `# SKILL.md — ${skillName}

## Description
${description}

## Usage
\`\`\`bash
# This skill was generated by Tool Forge.
# Implement the logic below.
\`\`\`

## Steps
1. TODO: implement main logic
2. TODO: add error handling
3. TODO: test output
`;

  const files: ForgeFile[] = [
    { path: "SKILL.md", content: skillMd },
    { path: "script.sh", content: `#!/usr/bin/env bash\n# ${skillName}\necho "Running ${skillName}..."\n` },
  ];

  res.json({ skillName, files, instructions: `Install with the 'Install to OpenClaw' button.` });
});

router.post("/tool-forge/install", async (req, res) => {
  const { skillName, files } = req.body as { skillName?: string; files?: ForgeFile[] };
  if (!skillName || !Array.isArray(files)) {
    res.status(400).json({ error: "skillName and files required" });
    return;
  }

  const skillsDir = path.join(os.homedir(), ".openclaw", "workspace", "skills", skillName);
  try {
    await fs.mkdir(skillsDir, { recursive: true });
    for (const file of files) {
      const filePath = path.join(skillsDir, path.basename(file.path));
      await fs.writeFile(filePath, file.content);
    }
    res.json({ success: true, message: `Skill '${skillName}' installed to ${skillsDir}` });
  } catch (err) {
    console.error("tool-forge install error:", err);
    res.status(500).json({ success: false, message: "Failed to install skill" });
  }
});

export const toolForgeRoutes = router;
